### ISSUE TITLE
Compatibility with PHP 5.6

### ISSUE THREAD

**Issue by BassemN** [mtdowling/cron-expression#142]
Hello,

Is there any chance to make this great library compatible with PHP 5.6?

Thanks

**Comment by dragonmantank** [comment]
Hello!

[Version 1.2.0](https://github.com/mtdowling/cron-expression/releases/tag/v1.2.0) will be the last release supporting PHP 5.x. This was released a few weeks ago to address a few issues. If you are using `dev-master` in your `composer.json` file I would recommend moving to one of the released tags. 

Going forward, the library will begin to support the PHP 7.x releases. PHP 5.6 was the last release for 5.x and has since moved into "Security Only" mode. There are also a lot of new features in PHP 7.x that we will be able to take advantage of.

**Comment by BassemN** [comment]
Thanks for your time :+1:
