### ISSUE TITLE
Can you release a 1.2.1 tag?

### ISSUE THREAD

**Issue by patrickcurl** [mtdowling/cron-expression#162]
I'm using laravel, and need the timezone functionality.. it's not currently in the 1.2 branch.. and laravel only uses ~1.0 in composer.json... a new tag should I think resolve that... and let me use the master branch.. 

`- laravel/framework v5.3.31 requires mtdowling/cron-expression ~1.0 -> satisfiable by mtdowling/cron-expression[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.1.0, v1.2.0] but these conflict with your requirements or minimum-stability.`

**Comment by dragonmantank** [comment]
`master` has backwards compatibility breaking changes with 1.x due to fixing how stepping through ranges work. I'll be working with Laravel to have their next release move to the 2.x branch.

2.x has been released over at https://github.com/dragonmantank/cron-expression with the latest fixes (more info available at http://ctankersley.com/2017/10/12/cron-expression-update/)
