### ISSUE TITLE
Wrong every N-month calculate

### ISSUE THREAD

**Issue by paulzi** [mtdowling/cron-expression#173]
```php
$cron = CronExpression::factory('35 4 1 */3 *');
echo $cron->getNextRunDate('2019-08-02 00:00:00')->format('Y-m-d H:i:s');
```
CRON run this expression at `2019-10-01 04:35:00`, but getNextRunDate() return `2019-09-01 04:35:00`.

**Comment by dragonmantank** [comment]
Hello there!

This package is no longer maintained, and has been moved over to https://github.com/dragonmantank/cron-expression.

That being said, this is an issue with the v1.x branch of the library, and has been fixed in v2.x and later. The issue was how we determined the offsets being used, and led to this issue. The fix for this was specifically part of the v2 release.

If you have any more problems, feel free to open an issue over at https://github.com/dragonmantank/cron-expression.
