### ISSUE TITLE
No way to pass DateTime with custom TimeZone to isDue

### ISSUE THREAD

**Issue by taylorotwell** [mtdowling/cron-expression#78]
In Laravel's scheduler component, we allow the user to specify a Timezone to evaluate the Cron against. However, cron-expression appears to always overwrite the timezone to the current application timezone, allowing no custom timezone to be set.

Is there any way this can be resolved?

**Comment by mtdowling** [comment]
I don't remember exactly why this was added really. This is what I got from the blame: https://github.com/mtdowling/cron-expression/commit/cbde1b5a2974c83a6926a7d387479f0e04bb93c7

I guess it's trying to normalize the timezone. I'm happy to make a change if needed.

**Comment by taylorotwell** [comment]
It appears we can maybe work around it on our end as well by passing a string representation instead of a DateTime object, though it does seem intuitively like the Timezone of the given DateTime object should be respected.

**Comment by taylorotwell** [comment]
Maybe I'm wrong there. Here is the PR someone is working on our side (https://github.com/laravel/framework/pull/7636) ... personally I kind of wonder if it should be fixed over here though.

**Comment by swekaj** [comment]
I agree it should be fixed here.  The library shouldn't be changing the timezone without giving the user the option to specify the timezone it changes to.  It's very important to use the correct timezone when checking to see if a cron expression is due since the expressions themselves are not timezone-aware.  If you create expressions for GMT-8:00, then the library will always be off by 8 hours if it's converting any DateTimes to GMT/UTC.

I remember a year or so ago, I modified my local copy of the library to accept an optional timezone in the `CronExression::factory()` method.  That timezone was then used for any `::isDue()` and similar calls.  Unfortunately that work has been lost (I had forgotten I did that when I updated to using composer), but I'd be willing to recreate it.

I think it'd be most useful to allow providing a default timezone in the `::factory()` method as well as allowing the user to override that by passing in a DateTime with the appropriate timezone set in `::isDue()` and similar.  If no default timezone is supplied, then the system's default is used where necessary.

I could probably work on this this weekend, if you'd like.

**Comment by DerManoMann** [comment]
Looks like this is not handled consistently across all of the public API.
getRunDate() does just clone the given date/time if it is a DateTime instance. So, calling getMultipleRunDates() with a properly set up $currentTime will respect the timezone as given on $currentTime.
I remember that was something I was working towards as I also use this to evaluate against different timezones.
My stand is that if a DateTime instance is given, the timezone set in that instance should be used. For strings or 'now' the default timezone should be used.

**Comment by taylorotwell** [comment]
Is there a suggested fix for this? Anything I can do?

**Comment by mtdowling** [comment]
It can be fixed. We need a PR that removes all of the timezone modifications from the library and any time a DateTime object will be modified, it's cloned.

**Comment by taylorotwell** [comment]
We fixed it on our end for now by passing a string representation of the
time.

**Comment by lioannou** [comment]
@mtdowling @dragonmantank - it looks like someone has made a PR for this issue here https://github.com/mtdowling/cron-expression/pull/115

Any chance of reviewing it - and potentially merging?

I've run into the same issue as @taylorotwell (ironically for inside a Laravel application) that I really need to support custom timezones...

**Comment by laurencei** [comment]
@taylorotwell - this can be closed now as functionality was merged today: https://github.com/mtdowling/cron-expression/pull/134

**Comment by dragonmantank** [comment]
This should have been corrected with #134, so closing.
