### ISSUE TITLE
More detailed instructions? 

### ISSUE THREAD

**Issue by OZ1SEJ** [mtdowling/cron-expression#88]
Could you please elaborate on the documentation? I've downloaded a zip with some php files in it, but I don't have a directory called /vendor on my machine, and I don't have a .phar file. How do I use this?

**Comment by simogeo** [comment]
See the following PR : https://github.com/mtdowling/cron-expression/pull/79/files

**Comment by dragonmantank** [comment]
As it was mentioned in the linked PR, we aren't looking to support this outside of Composer. 

Overall, you should be looking into using Composer for auto-loading and dependency management. This library does not have many dependencies outside of phpunit for unit testing, but that may change one day. Each dependency `cron-expression` may have may have their own dependencies. Using Composer is a pretty low barrier to entry.

If, for some reason, you cannot use Composer at all, this library uses PSR-0 as an autoloading standard. You can implement PSR-0 in your project and point it to using the `src/` directory of this library. That will make it so you do not have to keep an older "include"-style file that may become out of date with releases or as dependencies change.

PSR-0 is deprecated at this point, and this library may shift to PSR-4 in the future. Again, by using Composer this will be a non-issue for you, otherwise you will need to implement PSR-4 in your application. 

Hope this helps!
